version: "3.5"

x-marketplace: &marketplace-backend
  image: docker.io/uniquenetwork/marketplace-backend
  restart: unless-stopped
  env_file:
    - ./.env-local
  depends_on:
    - marketplace-postgres

services:
  marketplace-postgres:
    image: postgres:14.1-alpine
    container_name: marketplace-postgres
    env_file:
      - ./.env-local
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ../postgresql/marketplace:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  marketplace-api:
    container_name: marketplace-api
    ports:
      - 5000:5000
    <<: *marketplace-backend

  marketplace-escrow-unique:
    container_name: marketplace-escrow-unique
    command: [ "npm", "run", "escrow:unique" ]
    <<: *marketplace-backend

  marketplace-escrow-kusama:
    container_name: marketplace-escrow-kusama
    command: [ "npm", "run", "escrow:kusama" ]
    <<: *marketplace-backend

