name: Deploy to Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  before:
    name: Before
    runs-on: self-hosted
    environment: dev
    env:
      DOCKER_NETWORK: ${{ secrets.DOCKER_NETWORK }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker network
        run: if [ ! "$(docker network ls -f name=${{ secrets.DOCKER_NETWORK }} | grep ${{ secrets.DOCKER_NETWORK }})" ]; then docker network create --driver=overlay --attachable ${{ secrets.DOCKER_NETWORK }};fi
      - name: Docker stack
        run: docker stack deploy -c .github/services/devops.yml ${{ secrets.DOCKER_NETWORK }}
      - name: Db stack
        run: docker stack deploy -c .github/services/db.yml ${{ secrets.DOCKER_NETWORK }}

  build:
    name: Build docker image
    needs: before
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: docker build -t ghcr.io/uniquenetwork/unique-marketplace-checkout-api/checkout-market-back:dev . -f .docker/Dockerfile
      - name: Push to GitHub Registry
        run: docker push ghcr.io/uniquenetwork/unique-marketplace-checkout-api/checkout-market-back:dev

  migrate:
    name: Migrate DB
    needs: build
    runs-on: self-hosted
    environment: dev
    steps:
      - name: Migrate Postgres
        run: docker run --rm --network=${{ secrets.DOCKER_NETWORK }} -e POSTGRES_URL="postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}" ghcr.io/uniquenetwork/unique-marketplace-checkout-api/checkout-market-back:dev npm run migration:run

  deploy:
    name: Deploy
    needs: migrate
    runs-on: self-hosted
    environment: dev
    env:
      POSTGRES_URL: "postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
    steps:
      - uses: actions/checkout@v3
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker stack deploy --with-registry-auth -c .github/services/dev.yml ${{ secrets.DOCKER_NETWORK }}
